### ISSUE TITLE
Make it ImGui | C++

### ISSUE THREAD

**Issue by ROCKIv** [Linewalker/GTAVCSMM#1]
Hey! Im seeing the project and its very nice, its an incredible base for coders. But i think if you made it a c++ imgui project (like bigbase for example) i think i can say that it can be the best open-source mod menu/tool.

Why: 

~ Easier to use
~ More beautiful
~ The possibility to expand the project (people know more c++ than csharp, people can include a lot of stuff)
~ Do more stuff, it give more posibillities to made things, change ui and make a beautiful one, easier to add options, ui more changeable, etc

Why i dont make it for my own:

~ I dont understand csharp and i know how functions are called, etc.
~ Thats maybe why the source is not that famous, people do not know how to change it

Its a big change, but if u made it the project will be the best source for gta v.

**Comment by Linewalker** [comment]
Hi!

Well, you are right with your points. and believe me, if I would be able to get this urnning in c++, I already would have done it. I Just can program basic things in C# and don't understand C++. So I try to translate the LUA-Scripts to C# and get basic things running. Not nice but working (:
